## Pandas Lab Exercise (Kaggle Automobile Dataset)

We shall now test your skills in using Pandas package. We will be using the [automobiles Dataset](https://www.kaggle.com/nisargpatel/automobiles/data) from Kaggle.

Answer each question asked below wrt the automobiles dataset. Load pandas as pd and upload the Automobile.csv file as auto

In [1]:
import pandas as pd

**Load the Automobile dataset into variable "auto"**

In [6]:
import pandas as pd
df=pd.read_csv('/content/Automobile.csv');
df

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
197,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
198,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
199,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

**Check the head of the DataFrame.**

In [7]:
df.head()

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

**How many rows and columns are there?**

In [8]:
df.shape[0]#for rows it should be 0 becoz first element is 0 it is row

201

In [9]:
df.shape[1]#for col it should be 1 becoz second element is 1 it is

26

**What is the average Price of all cars in the dataset?**

In [11]:
avg=df['price'].mean()
avg

13207.129353233831

**Which is the cheapest make and costliest make of car in the lot?**

In [12]:
#cheapset
a=df.sort_values(by=['price'], ascending=True).head(1)
a[['make','price']]

       make  price
134  subaru   5118

In [13]:
#costilest

a=df.sort_values(by=['price'], ascending=False).head(1)
a[['make','price']]

             make  price
71  mercedes-benz  45400

**How many cars have horsepower greater than 100?**

In [14]:
#by using count
a=df[df['horsepower']>100]
a['horsepower'].count()

#by using shape function
a=df[df['horsepower']>100].shape[0]
a

90

**How many hatchback cars are in the dataset ?**

In [15]:
a=df['body_style']=='hatchback'

In [16]:
b=a.sum()
b

68

**What are the 3 most commonly found cars in the dataset?**

In [18]:
commonly_used_cars = df['make']

In [19]:
commonly_used_cars.value_counts().head(3)

make
toyota    32
nissan    18
mazda     17
Name: count, dtype: int64

**Someone purchased a car for 7099, what is the make of the car?**

In [21]:
a=df[df['price']==7099];
a['make']

87    nissan
Name: make, dtype: object

**Which cars are priced greater than 40000?**

In [22]:
priced=df[df['price']>40000];
priced['make']

15              bmw
70    mercedes-benz
71    mercedes-benz
Name: make, dtype: object

**Which are the cars that are both a sedan and priced less than 7000?**

In [23]:
cars=df[(df['body_style']=='sedan') & df['price']<7000]
cars['make']

0      alfa-romero
1      alfa-romero
2      alfa-romero
3             audi
4             audi
          ...
196          volvo
197          volvo
198          volvo
199          volvo
200          volvo
Name: make, Length: 201, dtype: object

 **Count the number of unique values in the `fuel_type` column.**

In [25]:
df['fuel_type'].nunique()

2

**List all the cars that have a horsepower between 100 and 200, and display their `make`, `horsepower`, and `price`.**

In [27]:
valuescars = df[(df['horsepower'] >= 100) & (df['horsepower'] <= 200)]
df[['make', 'horsepower', 'price']]

            make  horsepower  price
0    alfa-romero         111  13495
1    alfa-romero         111  16500
2    alfa-romero         154  16500
3           audi         102  13950
4           audi         115  17450
..           ...         ...    ...
196        volvo         114  16845
197        volvo         160  19045
198        volvo         134  21485
199        volvo         106  22470
200        volvo         114  22625

[201 rows x 3 columns]

**Find the average `city_mpg` and `highway_mpg` for each `body_style`.**

In [28]:
avg=df.groupby('body_style')[['city_mpg', 'highway_mpg']].mean()
avg

              city_mpg  highway_mpg
body_style
convertible  20.500000    26.000000
hardtop      21.625000    27.250000
hatchback    26.602941    32.382353
sedan        25.053191    30.574468
wagon        24.040000    28.720000

**What is the median `price` for each `make`?**

In [29]:
df.groupby('make')['price'].median()

make
alfa-romero      16500.0
audi             17580.0
bmw              22835.0
chevrolet         6295.0
dodge             7609.0
honda             7295.0
isuzu             8916.5
jaguar           35550.0
mazda            10595.0
mercedes-benz    32892.0
mercury          16503.0
mitsubishi        8499.0
nissan            8124.0
peugot           16630.0
plymouth          7609.0
porsche          33278.0
renault           9595.0
saab             15275.0
subaru            7894.0
toyota            9103.0
volkswagen        9737.5
volvo            18420.0
Name: price, dtype: float64

**List all cars that have a `wheel_base` greater than 100 and a `curb_weight` less than 2500.**

In [31]:
cars=df[(df['wheel_base']>100) & (df['curb_weight']<2500)]
cars['make']

9         bmw
10        bmw
169    toyota
170    toyota
171    toyota
172    toyota
173    toyota
Name: make, dtype: object

**Create a new column `price_per_hp` that calculates the price of the car per horsepower.**

In [32]:
df['price_per_hp']=df['price']/df['horsepower']
df

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price,price_per_hp
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495,121.576577
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500,148.648649
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500,107.142857
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,10.0,102,5500,24,30,13950,136.764706
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.40,8.0,115,5500,18,22,17450,151.739130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,9.5,114,5400,23,28,16845,147.763158
197,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,8.7,160,5300,19,25,19045,119.031250
198,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,mpfi,3.58,2.87,8.8,134,5500,18,23,21485,160.335821
199,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,idi,3.01,3.40,23.0,106,4800,26,27,22470,211.981132
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,9.5,114,5400,19,25,22625,198.464912

**Count how many cars have a `number_of_doors` as `four`.**

In [37]:
cars=(df['number_of_doors']=='four').sum()
cars

114

**Find the top 5 cars based on their `highway_mpg` and `price`.**

In [40]:
top_cars = df.groupby(['make']).agg({'highway_mpg': 'max', 'price': 'max'})
top_cars.sort_values(by=['highway_mpg', 'price'], ascending=[False, False]).head(5)
# by dropping the duplicates
#top_cars = df.sort_values(by=['highway_mpg', 'price'], ascending=[False, False]).drop_duplicates(subset=['make'])
#top_cars.head(5)

            highway_mpg  price
make
honda                54  12945
chevrolet            53   6575
nissan               50  19699
toyota               47  17669
volkswagen           46  13845

**How many cars have missing values in the `normalized_losses` column?**

In [48]:
df['normalized_losses'].isnull().sum()
df.columns

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'number_of_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'number_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price', 'price_per_hp'],
      dtype='object')

**Create a new column `car_age` that calculates the age of the car based on the `year_of_manufacture` (assume the current year is 2025).**

### The END